name: datsigma
channels:
  - conda-forge

dependencies:
  - h5py
  - hdf5
  - pandas
  - python=3.8
  - yaml
  - matplotlib
  - seaborn
  - numpy
  - pip
  - scipy
  - scikit-learn
  - tqdm
  - numpy
  - requests
  - ipywidgets
  - scikit-image
  - opencv
  - imagecodecs
  - leidenalg
  - scanpy
  - pip:
    - torch==1.7.1
    - spike-py
    - pyimzml
    - pyMSpec
    - tables
    - anndata
    - xgboost
    - shap
